/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExampleIndexRouteImport } from './routes/example/index'
import { Route as ExampleUsersRouteImport } from './routes/example/users'
import { Route as ExampleLoginRouteImport } from './routes/example/login'
import { Route as ExampleDashboardRouteImport } from './routes/example/dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleIndexRoute = ExampleIndexRouteImport.update({
  id: '/example/',
  path: '/example/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleUsersRoute = ExampleUsersRouteImport.update({
  id: '/example/users',
  path: '/example/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleLoginRoute = ExampleLoginRouteImport.update({
  id: '/example/login',
  path: '/example/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleDashboardRoute = ExampleDashboardRouteImport.update({
  id: '/example/dashboard',
  path: '/example/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example/dashboard': typeof ExampleDashboardRoute
  '/example/login': typeof ExampleLoginRoute
  '/example/users': typeof ExampleUsersRoute
  '/example/': typeof ExampleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/example/dashboard': typeof ExampleDashboardRoute
  '/example/login': typeof ExampleLoginRoute
  '/example/users': typeof ExampleUsersRoute
  '/example': typeof ExampleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/example/dashboard': typeof ExampleDashboardRoute
  '/example/login': typeof ExampleLoginRoute
  '/example/users': typeof ExampleUsersRoute
  '/example/': typeof ExampleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/example/dashboard'
    | '/example/login'
    | '/example/users'
    | '/example/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/example/dashboard'
    | '/example/login'
    | '/example/users'
    | '/example'
  id:
    | '__root__'
    | '/'
    | '/example/dashboard'
    | '/example/login'
    | '/example/users'
    | '/example/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExampleDashboardRoute: typeof ExampleDashboardRoute
  ExampleLoginRoute: typeof ExampleLoginRoute
  ExampleUsersRoute: typeof ExampleUsersRoute
  ExampleIndexRoute: typeof ExampleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/': {
      id: '/example/'
      path: '/example'
      fullPath: '/example/'
      preLoaderRoute: typeof ExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/users': {
      id: '/example/users'
      path: '/example/users'
      fullPath: '/example/users'
      preLoaderRoute: typeof ExampleUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/login': {
      id: '/example/login'
      path: '/example/login'
      fullPath: '/example/login'
      preLoaderRoute: typeof ExampleLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/dashboard': {
      id: '/example/dashboard'
      path: '/example/dashboard'
      fullPath: '/example/dashboard'
      preLoaderRoute: typeof ExampleDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExampleDashboardRoute: ExampleDashboardRoute,
  ExampleLoginRoute: ExampleLoginRoute,
  ExampleUsersRoute: ExampleUsersRoute,
  ExampleIndexRoute: ExampleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
