/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExampleIndexRouteImport } from './routes/example/index'
import { Route as ExampleProductsRouteImport } from './routes/example/products'
import { Route as ExamplePosRouteImport } from './routes/example/pos'
import { Route as ExampleLoginRouteImport } from './routes/example/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleIndexRoute = ExampleIndexRouteImport.update({
  id: '/example/',
  path: '/example/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleProductsRoute = ExampleProductsRouteImport.update({
  id: '/example/products',
  path: '/example/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplePosRoute = ExamplePosRouteImport.update({
  id: '/example/pos',
  path: '/example/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const ExampleLoginRoute = ExampleLoginRouteImport.update({
  id: '/example/login',
  path: '/example/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/example/login': typeof ExampleLoginRoute
  '/example/pos': typeof ExamplePosRoute
  '/example/products': typeof ExampleProductsRoute
  '/example/': typeof ExampleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/example/login': typeof ExampleLoginRoute
  '/example/pos': typeof ExamplePosRoute
  '/example/products': typeof ExampleProductsRoute
  '/example': typeof ExampleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/example/login': typeof ExampleLoginRoute
  '/example/pos': typeof ExamplePosRoute
  '/example/products': typeof ExampleProductsRoute
  '/example/': typeof ExampleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/example/login'
    | '/example/pos'
    | '/example/products'
    | '/example/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/example/login' | '/example/pos' | '/example/products' | '/example'
  id:
    | '__root__'
    | '/'
    | '/example/login'
    | '/example/pos'
    | '/example/products'
    | '/example/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExampleLoginRoute: typeof ExampleLoginRoute
  ExamplePosRoute: typeof ExamplePosRoute
  ExampleProductsRoute: typeof ExampleProductsRoute
  ExampleIndexRoute: typeof ExampleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/': {
      id: '/example/'
      path: '/example'
      fullPath: '/example/'
      preLoaderRoute: typeof ExampleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/products': {
      id: '/example/products'
      path: '/example/products'
      fullPath: '/example/products'
      preLoaderRoute: typeof ExampleProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/pos': {
      id: '/example/pos'
      path: '/example/pos'
      fullPath: '/example/pos'
      preLoaderRoute: typeof ExamplePosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/example/login': {
      id: '/example/login'
      path: '/example/login'
      fullPath: '/example/login'
      preLoaderRoute: typeof ExampleLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExampleLoginRoute: ExampleLoginRoute,
  ExamplePosRoute: ExamplePosRoute,
  ExampleProductsRoute: ExampleProductsRoute,
  ExampleIndexRoute: ExampleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
